version: "3.9" # optional since v1.27.0
services:
  web:
    build: client-side
    ports:
      - "8080:8080"

  test_tool:
    build: ./server-side/test_tool/test_tool
    ports:
      - "1234:8080"
  mongo:
    image: mongo

  server:
    depends_on:
      - mongo
    build: server-side
    ports:
      - "8010:8010"
