version: "3.9" # optional since v1.27.0
services:
  web:
    build: client-side

    volumes:
      - ./client-side/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./client-side/conf.d/proxy.conf:/etc/nginx/includes/proxy.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  mongo:
    image: mongo

  server:
    depends_on:
      - mongo
    build: server-side
    ports:
      - "8010:8010"
